services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Verclam\DoctrineFilterPaginator\:
        resource: '../src/'
        exclude:
            - '../src/VerclamDoctrineFilterPaginatorBundle.php'
            - '../src/Attributes/'
            - '../src/DTO/'
            - '../src/Enum/'
            - '../src/Interfaces/'

    Verclam\DoctrineFilterPaginator\FilterPagerManager:
        public: true

    verclam.doctrine_filter_paginator.date_utils:
        class: Verclam\DoctrineFilterPaginator\Utils\DateUtils
        arguments:
            $timezone: 'Europe/Paris'
